default_stages: [ pre-commit, pre-push ]
exclude: ^src/(bin/|web_interface/static/package-lock.json)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=10000 ]

      - id: check-json

      - id: check-merge-conflict

      - id: check-toml

      - id: check-yaml

      - id: fix-encoding-pragma
        args: [ --remove ]

      - id: file-contents-sorter
        files: src/unpacker/passwords|_list.txt

      - id: forbid-new-submodules

      - id: no-commit-to-branch

      - id: pretty-format-json
        args: [ --autofix ]
        exclude: ^src/web_interface/static/package-lock.json

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint

  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.6
    hooks:
      - id: jshint

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.14.11'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [ "--config", ".markdownlint.yaml" ]
