default_stages: [commit, push]
exclude: ^src/bin/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=10000]

    -   id: check-json

    -   id: check-merge-conflict

    -   id: check-toml

    -   id: check-yaml

    -   id: fix-encoding-pragma
        args: [--remove]

    -   id: file-contents-sorter
        files: src/unpacker/passwords|_list.txt

    -   id: forbid-new-submodules

    -   id: no-commit-to-branch

    -   id: pretty-format-json
        args: [--autofix]

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    -   id: shellcheck

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint

-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.0
    hooks:
    -   id: jshint

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.2.2'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
