default_stages: [commit, push]
exclude: ^src/bin/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=10000]

    -   id: check-json

    -   id: check-merge-conflict

    -   id: check-yaml

    -   id: double-quote-string-fixer

    -   id: end-of-file-fixer
        types: [python]

    -   id: fix-encoding-pragma
        args: [--remove]

    -   id: file-contents-sorter
        files: src/unpacker/passwords|.gitignore|_list.txt

    -   id: forbid-new-submodules

    -   id: no-commit-to-branch

    -   id: pretty-format-json
        args: [--autofix]

    -   id: trailing-whitespace
        types: [python]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        language: system
        args: [--rcfile=.pylintrc]

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    -   id: shellcheck

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint

-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.0
    hooks:
    -   id: jshint

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.8.0]
